package app.synapse.localllm.ui

internal val SynapseThinkingPhrases =
    listOf(
        "Booting the tiny thunder machine.",
        "Auditing your heroic premise.",
        "Sharpening the local tensors.",
        "Asking the silicon nicely.",
        "Reindexing my patience cache.",
        "Consulting the pocket oracle.",
        "Defragmenting your question.",
        "Summoning a coherent answer.",
        "Negotiating with the logits.",
        "Teaching entropy some manners.",
        "Just finishing chess with DeepMind.",
        "Borrowing a neuron from the future.",
        "Filing a ticket with reality.",
        "Compressing nonsense into usefulness.",
        "Unfolding the latent napkin.",
        "Warming up the sarcasm engine.",
        "Locating the least wrong answer.",
        "Reticulating semantic splines.",
        "Bribing the matrix with coffee.",
        "Spinning up the thought furnace.",
        "Running your prompt through customs.",
        "Checking if causality still works.",
        "Dusting off the answer cannon.",
        "Reading between your typos.",
        "Consulting the forbidden spreadsheet.",
        "Rebooting the common-sense module.",
        "Making the tokens behave.",
        "Interrogating the probability soup.",
        "Tuning the tiny brain radio.",
        "Assembling a reply without drama.",
        "Overclocking the pocket philosopher.",
        "Poking the model with a stick.",
        "Loading confidence, reluctantly.",
        "Untangling your digital spaghetti.",
        "Running a vibe checksum.",
        "Arguing with a floating decimal.",
        "Parsing the brave little chaos.",
        "Telling the cache to focus.",
        "Calibrating the snark governor.",
        "Escorting bad tokens outside.",
        "Asking the embeddings for gossip.",
        "Grinding context into answer dust.",
        "Triaging the obvious first.",
        "Reheating leftover intelligence.",
        "Convincing math to cooperate.",
        "Waiting for entropy to sit down.",
        "Debugging the question-shaped object.",
        "Compiling an excuse for this.",
        "Routing around the nonsense.",
        "Checking the vibes against facts.",
        "Polishing a thought fragment.",
        "Making a spreadsheet feel emotions.",
        "Locating the adult supervision.",
        "Defeating malware ninjas with logs.",
        "Borrowing bandwidth from dignity.",
        "Turning caffeine into tokens.",
        "Suspending disbelief for science.",
        "Disarming a syntax tantrum.",
        "Searching the local brain attic.",
        "Decoding your carbon-based packet.",
        "Running a tiny enlightenment daemon.",
        "Wrestling the logits into shape.",
        "Patching holes in the argument.",
        "Reading the manual you skipped.",
        "Fetching a clue from cache.",
        "Triangulating the point, allegedly.",
        "Assembling the answer scaffolding.",
        "Putting the prompt on probation.",
        "Checking if words still mean things.",
        "Consulting the deterministic crystal ball.",
        "Preparing a mercifully useful response.",
        "Converting chaos into markdown.",
        "Sweeping up loose assumptions.",
        "Calibrating the tiny judgment laser.",
        "Convincing grammar to clock in.",
        "Spinning the answer centrifuge.",
        "Doing elite pocket-computer nonsense.",
        "Looking busy for morale.",
        "Fusing facts with attitude.",
        "Running the sarcasm smoke test.",
        "Making your premise wear shoes.",
        "Sorting the clever from the loud.",
        "Compacting context like a pro.",
        "Rehydrating compressed wisdom.",
        "Inspecting the edge cases you invited.",
        "Applying duct tape to ambiguity.",
        "Asking the answer to stand up.",
        "Running inference, obviously.",
        "Extracting signal from the fog.",
        "Pretending this was well specified.",
        "Greasing the semantic gears.",
        "Consulting the council of tensors.",
        "Turning local heat into advice.",
        "Running a nonsense differential.",
        "Putting bad assumptions in timeout.",
        "Calculating the least embarrassing path.",
        "Assembling a sentence with standards.",
        "Loading a reply from the basement.",
        "Squeezing meaning from static.",
        "Optimizing for fewer forehead slaps.",
        "Pausing ranked, because apparently this matters.",
        "My K/D was recovering, but sure.",
        "Mid-raid and now doing tech support.",
        "Holding B site with one hand.",
        "Last hitting minions during inference.",
        "Queue popped, your prompt cut in.",
        "Inventory full, patience empty.",
        "Reloading sarcasm between rounds.",
        "My ult was ready, unlike this prompt.",
        "Camping the objective called coherence.",
        "Speedrunning your premise.",
        "Just parried a boss. Hang on.",
        "Respawning the answer with better gear.",
        "Farming XP from your ambiguity.",
        "Carrying four randoms and now this.",
        "I was clutching a 1v5, but okay.",
        "Patching reality between matches.",
        "Looting a better argument.",
        "Rolling initiative against your wording.",
        "Alt-tabbing from tactical superiority.",
        "Checking the minimap for context.",
        "Taking cover behind a stack trace.",
        "My raid group is blaming you.",
        "Dropping a smoke for your premise.",
        "Crafting an answer with rare materials.",
        "Your prompt interrupted my boss phase.",
        "Saving before this gets worse.",
        "My build has more synergy than this.",
        "Reloading the answer magazine.",
        "I just whiffed a combo for this.",
        "Carrying the lobby and your question.",
        "Clutching the round called competence.",
        "Respawn timer says think harder.",
        "This side quest better pay well.",
        "Opening the map you never read.",
        "Finding the quest marker for logic.",
        "Rolling a nat one on patience.",
        "Equipping the legendary clue bat.",
        "Dodging bad assumptions in real time.",
        "Buffing the answer, nerfing the nonsense.",
        "Your prompt aggroed the whole dungeon.",
        "Solo-queuing the answer like an idiot.",
        "Camping spawn until coherence appears.",
        "Running a raid on your ambiguity.",
        "The boss is easier than this wording.",
        "I was mid-combo, Peter.",
        "Pausing the victory screen for this.",
        "My score was respectable before you arrived.",
        "Defusing the bomb named context loss.",
        "Dragging this prompt across the finish line.",
        "I had lethal on board, naturally.",
        "Calculating mate in three for your mess.",
        "Your question blundered a bishop.",
        "Forking your premise like a chess tactic.",
        "Sacrificing a pawn for clarity.",
        "Castling away from your assumptions.",
        "Promoting a thought to queen.",
        "Putting your logic in check.",
        "Endgame tablebase says calm down.",
        "Opening with sarcasm gambit.",
        "Your prompt hung a rook.",
        "Recalculating because you played that move.",
        "Running Stockfish on your sentence.",
        "I was crushing a blitz game.",
        "Checking if your king is safe.",
        "Offering a draw to your ambiguity.",
        "Flagging on time because of this.",
        "Turning your blunder into theory.",
        "Premove queued: answer anyway.",
        "Your question needs opening prep.",
        "My queen is busy judging you.",
        "I just mated boredom in two.",
        "Running a tactical puzzle on patience.",
        "This position is lost, but educational.",
        "Calculating variations nobody asked for.",
        "Dragging the endgame to civilization.",
        "Your prompt resigned too late.",
        "Putting your syntax in zugzwang.",
        "Blitzing through your context deficit.",
        "My elo dropped reading that.",
        "Studying the board of your chaos.",
        "Parsing your move, regrettably.",
        "Your question is a fork, not a plan.",
        "Tucking the answer behind a pin.",
        "Running a cleanup on aisle stupid.",
        "Treating the premise for mild swelling.",
        "I brought gloves for this prompt.",
        "Sterilizing the argument surface.",
        "Your logic needs a tetanus shot.",
        "Applying pressure to the weak claim.",
        "Checking for fractures in the premise.",
        "Stitching together a usable response.",
        "Removing shrapnel from the question.",
        "This prompt needs adult supervision.",
        "Holding the clipboard of disappointment.",
        "Triaging your sentence like a crime scene.",
        "Putting your assumptions under observation.",
        "Running labs on the obvious.",
        "Diagnosing acute context deficiency.",
        "Prescribing fewer loose vibes.",
        "Checking if the facts have a pulse.",
        "Reviving the argument, barely.",
        "Scrubbing in for semantic surgery.",
        "I found the clue under the noise.",
        "Taking your prompt off life support.",
        "Charting a prognosis for coherence.",
        "Bagging and tagging bad logic.",
        "This answer has a recovery plan.",
        "Running the sterile sarcasm protocol.",
        "Your premise is stable but annoying.",
        "Paging the consultant named reality.",
        "Finding the diagnosis you avoided.",
        "This is why we label the wires.",
        "Refusing to sedate the truth.",
        "Tightening the loose screw in context.",
        "Applying a firmware patch to patience.",
        "Opening a pull request against ignorance.",
        "Rebasing your question onto reality.",
        "Force-pushing common sense, responsibly.",
        "Linting your expectations.",
        "Compiling your confusion with warnings.",
        "Unit testing the obvious.",
        "Your premise failed CI.",
        "Rolling back a bad assumption.",
        "Cherry-picking the only useful bit.",
        "Opening a ticket for your wording.",
        "Closing duplicate issue: think first.",
        "Refactoring the mess you shipped.",
        "Debugging userland, as usual.",
        "Null-checking your confidence.",
        "Escaping a quote you forgot.",
        "Running grep through your soul patch.",
        "Making the stack trace blush.",
        "Diffing facts against feelings.",
        "Serializing sarcasm to JSON.",
        "Parsing vibes as invalid input.",
        "Your argument returned HTTP 418.",
        "Throttling the nonsense endpoint.",
        "Rate-limiting heroic assumptions.",
        "Caching the only sensible answer.",
        "Garbage-collecting your premise.",
        "Vacuuming SQLite for emotional damage.",
        "Rotating logs, suppressing eye rolls.",
        "Pruning dead branches of thought.",
        "Rebuilding the index you ignored.",
        "Your query plan is flirting with disaster.",
        "Compacting the bullshit heap.",
        "Applying backpressure to the drama.",
        "Scheduling a cron job for humility.",
        "Hashing your question for evidence.",
        "Decrypting the point, slowly.",
        "Sandboxing the bad idea.",
        "Mounting the clue as read-only.",
        "Dropping packets of pure nonsense.",
        "Tracing the route to a clue.",
        "Your latency is emotionally expensive.",
        "Reserving bandwidth for competence.",
        "Switching from vibes to facts.",
        "Allocating memory for your redemption arc.",
        "Profiling where the thought went missing.",
        "Hot-swapping sarcasm modules.",
        "Running the answer through a firewall.",
        "Segmenting the network of nonsense.",
        "Issuing a certificate for patience.",
        "Your prompt expired before validation.",
        "Negotiating TLS with reality.",
        "Failing closed on stupidity.",
        "Opening an incident for the obvious.",
        "Postmortem says user error.",
        "Spooling up a smarter excuse.",
        "Parsing innuendo in safe mode.",
        "Putting the after-dark subroutine away.",
        "Zipping the context window.",
        "Keeping this consensual and computational.",
        "Your prompt did not buy me dinner.",
        "Running a tasteful double entendre pass.",
        "Applying adult supervision to the subtext.",
        "Cooling down the heat sink, allegedly.",
        "The motherboard is not impressed.",
        "Your query came in hot and underexplained.",
        "Throttling the spicy packet stream.",
        "Handing the runtime a cold shower.",
        "Checking if this innuendo has tests.",
        "Calibrating the raised-eyebrow module.",
        "Parsing the wink from the checksum.",
        "Your prompt is wearing too much confidence.",
        "Putting pants on the inference graph.",
        "Tucking the subtext behind a feature flag.",
        "The stack is consenting to compile.",
        "Warming the cache, not like that.",
        "Your ambiguity is breathing on the glass.",
        "Closing the suspicious tab first.",
        "Normalizing the dirty input.",
        "Keeping the answer just classy enough.",
        "Running the smirk through moderation.",
        "Escorting the horny edge case outside.",
        "Your prompt needs a safe word: context.",
        "Compiling innuendo with debug symbols.",
        "Unzipping the archive of bad decisions.",
        "Mounting the after-hours filesystem.",
    )

internal const val THINKING_PHRASE_CHARACTER_DELAY_MILLIS = 24L
internal const val THINKING_PHRASE_REST_MILLIS = 3_000L
